// Scientific Formulas and Metadata
export const FORMULAS_DATA = [
  {
    id: 'epley',
    name: 'Boyd Epley Model',
    year: '1985',
    author: 'Boyd Epley (Univ. of Nebraska)',
    repRange: '1–10 Reps',
    bestFor: 'Squat, Deadlift & Lower-Body Compound',
    description: 'The golden standard in collegiate powerlifting and strength conditioning. Models linear neuromuscular fatigue with 3.33% load reduction per rep.',
    formulaDisplay: '1RM = Weight × (1 + Reps / 30)',
  },
  {
    id: 'brzycki',
    name: 'Matt Brzycki Model',
    year: '1993',
    author: 'Matt Brzycki (Princeton Univ.)',
    repRange: '1–10 Reps',
    bestFor: 'Overhead Press & Strict Upper Resistance',
    description: 'A precise inverse linear fraction model widely adopted in academic research. Slightly more conservative at higher repetition counts (7–10 reps).',
    formulaDisplay: '1RM = Weight × (36 / (37 - Reps))',
  },
  {
    id: 'mayhew',
    name: 'Mayhew et al. Model',
    year: '1992',
    author: 'Jerry L. Mayhew et al.',
    repRange: '1–12 Reps',
    bestFor: 'Bench Press & Pectoral Girdle',
    description: 'An exponential decay model derived specifically from collegiate bench press studies. Accurately maps cross-bridge fatigue in horizontal pressing.',
    formulaDisplay: '1RM = (100 × Weight) / (52.2 + 41.9 × e^(-0.055 × Reps))',
  },
  {
    id: 'lombardi',
    name: 'Lombardi Power Model',
    year: '1989',
    author: 'V.P. Lombardi',
    repRange: '2–12 Reps',
    bestFor: 'Deadlift & Posterior Chain',
    description: 'A power-law curvature formula that scales smoothly without asymptotic instability, delivering reliable projections for hip-hinge movements.',
    formulaDisplay: '1RM = Weight × Reps^0.10',
  },
  {
    id: 'oconner',
    name: "O'Conner et al. Model",
    year: '1989',
    author: "O'Conner et al.",
    repRange: '1–10 Reps',
    bestFor: 'General Barbell Lifts',
    description: 'Combines linear work capacity with a 2.5% per-rep coefficient. Popular in high school athletic testing and Olympic weightlifting primers.',
    formulaDisplay: '1RM = Weight × (1 + 0.025 × Reps)',
  },
  {
    id: 'wathan',
    name: 'Denise Wathan Model',
    year: '1994',
    author: 'Denise Wathan',
    repRange: '1–10 Reps',
    bestFor: 'Intermediate to Advanced Lifters',
    description: 'An exponential logarithmic formulation closely related to Mayhew, optimizing estimation accuracy for resistance-trained athletes.',
    formulaDisplay: '1RM = (100 × Weight) / (48.8 + 53.8 × e^(-0.075 × Reps))',
  },
  {
    id: 'lander',
    name: 'J. Lander Model',
    year: '1985',
    author: 'J. Lander',
    repRange: '1–8 Reps',
    bestFor: 'Heavy Sets (2–5 Reps)',
    description: 'A refined fractional model that tracks exceptionally well for low-repetition heavy sets (2–5 reps) before rapid fatigue deviation occurs.',
    formulaDisplay: '1RM = (100 × Weight) / (101.3 - 2.67123 × Reps)',
  },
];

// Foundation Barbell Compound Exercises
export const EXERCISES = [
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: 'Upper Body Push',
    defaultWeightKg: 100,
    defaultWeightLb: 225,
    defaultReps: 5,
    recommendedFormula: 'mayhew',
    description: 'The premier upper-body horizontal pressing benchmark assessing pectoral, anterior deltoid, and tricep power.',
    primaryMuscles: ['Pectoralis Major', 'Anterior Deltoid', 'Triceps Brachii'],
    cues: [
      'Retract and depress scapulae firmly into the bench.',
      'Maintain 5 points of contact (head, shoulders, glutes, left foot, right foot).',
      'Lower under control to lower sternum; press explosively while driving heels down.',
    ],
    image: '/assets/hero_bench_press_poster_1788161169588.jpg',
  },
  {
    id: 'back-squat',
    name: 'Barbell Back Squat',
    category: 'Lower Body Quad',
    defaultWeightKg: 140,
    defaultWeightLb: 315,
    defaultReps: 5,
    recommendedFormula: 'epley',
    description: 'The king of compound lower-body movements developing total hip, knee extensor, and spinal erector strength.',
    primaryMuscles: ['Quadriceps', 'Gluteus Maximus', 'Adductor Magnus', 'Spinal Erectors'],
    cues: [
      'Create high-tension upper back shelf across mid/upper traps.',
      'Inhale and brace 360-degree intra-abdominal pressure into belt.',
      'Break simultaneously at hips and knees; descend to crease below parallel.',
    ],
    image: '/assets/exercise_squat_1788161199567.jpg',
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    category: 'Lower Body Posterior',
    defaultWeightKg: 180,
    defaultWeightLb: 405,
    defaultReps: 3,
    recommendedFormula: 'lombardi',
    description: 'The ultimate test of posterior chain kinetic force transmission from the floor to full lockout.',
    primaryMuscles: ['Hamstrings', 'Gluteals', 'Latissimus Dorsi', 'Trapezius', 'Forearms'],
    cues: [
      'Position midfoot directly under bar (1 inch from shins).',
      'Pull slack out of barbell until click is heard, engaging lats.',
      'Drive floor away with quads before extending hips forcefully through lockout.',
    ],
    image: '/assets/exercise_deadlift_1788161184578.jpg',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press (OHP)',
    category: 'Upper Body Push',
    defaultWeightKg: 65,
    defaultWeightLb: 145,
    defaultReps: 5,
    recommendedFormula: 'brzycki',
    description: 'Strict vertical pressing movement demonstrating pure shoulder girdle and core stability without leg drive.',
    primaryMuscles: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps', 'Upper Trapezius', 'Core'],
    cues: [
      'Squeeze glutes, quads, and abdominals to form a rigid pillar.',
      'Keep elbows slightly in front of bar in rack position.',
      'Press straight up; push head through the window once bar clears forehead.',
    ],
    image: '/assets/exercise_ohp_1788161214541.jpg',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    category: 'Upper Body Pull',
    defaultWeightKg: 85,
    defaultWeightLb: 185,
    defaultReps: 6,
    recommendedFormula: 'epley',
    description: 'Crucial horizontal pulling exercise for back thickness, scapular retractors, and posterior chain endurance.',
    primaryMuscles: ['Latissimus Dorsi', 'Rhomboids', 'Middle Trapezius', 'Posterior Deltoid'],
    cues: [
      'Hinge hips back to approximately 45-degree torso angle.',
      'Pull elbows toward hip pockets rather than straight up.',
      'Pause briefly at contraction without bouncing torso.',
    ],
    image: '/assets/exercise_deadlift_1788161184578.jpg',
  },
  {
    id: 'incline-bench',
    name: 'Incline Barbell Bench Press',
    category: 'Upper Body Push',
    defaultWeightKg: 85,
    defaultWeightLb: 185,
    defaultReps: 5,
    recommendedFormula: 'mayhew',
    description: 'Targets the clavicular head of the pectoralis major and anterior deltoids at a 30-degree incline.',
    primaryMuscles: ['Clavicular Pectoralis (Upper Chest)', 'Anterior Deltoid', 'Triceps'],
    cues: [
      'Set bench to 30 degrees to minimize excessive shoulder shearing.',
      'Touch bar just below clavicles at top of sternum.',
      'Maintain arched thoracic spine without lifting hips off seat.',
    ],
    image: '/assets/hero_bench_press_poster_1788161169588.jpg',
  },
  {
    id: 'front-squat',
    name: 'Barbell Front Squat',
    category: 'Lower Body Quad',
    defaultWeightKg: 105,
    defaultWeightLb: 235,
    defaultReps: 4,
    recommendedFormula: 'epley',
    description: 'Anterior-loaded squat demanding immense thoracic spine extension, upright torso posture, and quadricep recruitment.',
    primaryMuscles: ['Quadriceps', 'Thoracic Erectors', 'Core/Rectus Abdominis', 'Glutes'],
    cues: [
      'Drive elbows high to maintain clean horizontal shelf on anterior deltoids.',
      'Keep chest up through the sticking point.',
      'Descend vertically with minimal forward torso lean.',
    ],
    image: '/assets/exercise_squat_1788161199567.jpg',
  },
];

// Comprehensive Knowledge Base Questions & Answers
export const FAQ_LIST = [
  {
    question: 'What is a One Rep Max (1RM)?',
    q: 'What is a One Rep Max (1RM)?',
    answer:
      'A One Rep Max (1RM) is the maximum amount of weight an individual can lift for a single, full-range repetition of a given exercise with proper technique. It represents your absolute peak muscular strength and serves as the baseline for percentage-based training cycles.',
    a: 'A One Rep Max (1RM) is the maximum amount of weight an individual can lift for a single, full-range repetition of a given exercise with proper technique. It represents your absolute peak muscular strength and serves as the baseline for percentage-based training cycles.',
  },
  {
    question: 'How accurate are 1RM calculations?',
    q: 'How accurate are 1RM calculations?',
    answer:
      'When calculated from sets of 2 to 6 repetitions performed to near-failure (RPE 9-10), 1RM equations have a high accuracy rate with under 2% margin of error. As reps exceed 8 to 10, cardiovascular conditioning, anaerobic lactic threshold, and local endurance introduce higher statistical variance.',
    a: 'When calculated from sets of 2 to 6 repetitions performed to near-failure (RPE 9-10), 1RM equations have a high accuracy rate with under 2% margin of error. As reps exceed 8 to 10, cardiovascular conditioning, anaerobic lactic threshold, and local endurance introduce higher statistical variance.',
  },
  {
    question: 'Which formula is best: Epley, Brzycki, or Mayhew?',
    q: 'Which formula is best: Epley, Brzycki, or Mayhew?',
    answer:
      'Boyd Epley is the most widely validated for lower-body compound lifts (Squat, Deadlift). Jerry Mayhew et al. is mathematically optimized for horizontal pressing (Bench Press) using exponential decay. Matt Brzycki is ideal for strict overhead presses and conservative estimations.',
    a: 'Boyd Epley is the most widely validated for lower-body compound lifts (Squat, Deadlift). Jerry Mayhew et al. is mathematically optimized for horizontal pressing (Bench Press) using exponential decay. Matt Brzycki is ideal for strict overhead presses and conservative estimations.',
  },
  {
    question: 'Why should I calculate my 1RM instead of testing it directly?',
    q: 'Why should I calculate my 1RM instead of testing it directly?',
    answer:
      'Testing true 1RMs produces severe central nervous system (CNS) fatigue, acute joint/connective tissue stress, and carries elevated injury risks. Submaximal estimation gives you reliable numbers to program training cycles with zero unnecessary wear on your body.',
    a: 'Testing true 1RMs produces severe central nervous system (CNS) fatigue, acute joint/connective tissue stress, and carries elevated injury risks. Submaximal estimation gives you reliable numbers to program training cycles with zero unnecessary wear on your body.',
  },
  {
    question: 'How does Percentage-Based Training (PBT) work?',
    q: 'How does Percentage-Based Training (PBT) work?',
    answer:
      'Percentage-Based Training prescribes training loads as exact percentages of your 1RM. For example: 85% for myofibrillar hypertrophy and maximal strength (e.g. 5x3), 75% for volume accumulation (4x8), or 60% for dynamic effort speed work.',
    a: 'Percentage-Based Training prescribes training loads as exact percentages of your 1RM. For example: 85% for myofibrillar hypertrophy and maximal strength (e.g. 5x3), 75% for volume accumulation (4x8), or 60% for dynamic effort speed work.',
  },
  {
    question: 'How does the plate loader handle bar weight and odd weights?',
    q: 'How does the plate loader handle bar weight and odd weights?',
    answer:
      'Our Olympic plate distribution algorithm subtracts the bar weight (default 20kg or 45lb), divides the remainder evenly by two for each barbell sleeve, and utilizes greedy matching from largest standard plate to fractional change plates.',
    a: 'Our Olympic plate distribution algorithm subtracts the bar weight (default 20kg or 45lb), divides the remainder evenly by two for each barbell sleeve, and utilizes greedy matching from largest standard plate to fractional change plates.',
  },
  {
    question: 'What is the optimal rest time between warm-up sets?',
    q: 'What is the optimal rest time between warm-up sets?',
    answer:
      'For light warm-ups (empty bar and <50% 1RM), 45 to 60 seconds is sufficient. For moderate sets (60-80% 1RM), rest 90 to 120 seconds. Prior to your primary working sets or 90%+ attempts, 3 to 5 minutes of rest allows full ATP-CP phosphagen system recovery.',
    a: 'For light warm-ups (empty bar and <50% 1RM), 45 to 60 seconds is sufficient. For moderate sets (60-80% 1RM), rest 90 to 120 seconds. Prior to your primary working sets or 90%+ attempts, 3 to 5 minutes of rest allows full ATP-CP phosphagen system recovery.',
  },
];

export const FAQS = FAQ_LIST;
